# %% [markdown]
### Alfabeti Shqip - Language Learning Flaschard Set

# %% [markdown]
# Developed by Alex Sessums

# %%
# Import Libraries

from tkinter import *
from random import randint

root = Tk()
root.title("Alfabeti Shqip Flashcards")
# root.iconbitmap('/Users/asessums/Desktop/personal_projects/shqiper/Shqiper\ Flashcard\ Set.ipynb')
root.geometry("550x410")

# %%
# Shqip Words

words = [(("Që"), ("That")),
         (("Anije"), ("Ship")), 
         (("Akullore"), ("Ice Cream")), 
         (("Ara"), ("Walnut")), 
         (("Jam i/e lodhur!"), ("I am tired")),
         (("Dua të fle!"), ("I want to sleep")),
         (("Jam e uritur!"), ("I am hungry")),
         (("Dua të ha!"), ("I want to eat")),
         (("Dhoma është e ftohtë"), ("The room is cold")),
         (("Dua batanije"), ("I want a blanket")),
         (("Dhoma është e ngrohtë"), ("The room is warm")),
         (("Nuk dua batanije"), ("I do not want a blanket")),
         (("Po shkoj në dhomë"), ("I am going to my room")),
         (("Ushqime dhe pije"), ("Food and Drink")),
         (("bukë"), ("bread")),
         (("gjalpë"), ("butter")),
         (("djathë"), ("cheese")),
         (("makarona"), ("pasta")),
         (("miell"), ("flour")),
         (("oriz"), ("rice")),
         (("vezë"), ("egg")),
         (("sallatë"), ("salad")),
         (("kripë"), ("salt")),
         (("vaj"), ("oil")),
         (("Fruta dhe perime"), ("Fruit and vegetables")),
         (("Rrush"), ("Grapes")),
         (("Portokall"), ("Orange")),
         (("Domate"), ("Tomato")),
         (("Molle"), ("Apple")),
         (("Spec"), ("Pepper")), 
         (("Qepë"), ("Onion")), 
         (("Dardhë"), ("Pear")), 
         (("Presh"), ("Leek")), 
         (("Bamje"), ("Okra")), 
         (("Si"), ("As")), 
         (("Si"), ("As")), 
         (("I"), ("I")), 
         (("E Tij"), ("His")),
(("Që"), ("That")),
(("Ai"), ("He")),
(("Ishte"), ("Was")),
(("Për"), ("For")),
(("Në"), ("On")),
(("Janë"), ("Are")),
(("Me"), ("With")),
(("Ata"), ("They")),
(("Jetë"), ("Be")),
(("Në"), ("At")),
(("Një"), ("One")),
(("Kam"), ("Have")),
(("Kjo"), ("This")),
(("Nga"), ("From")),
(("Nga"), ("By")),
(("Hot"), ("Hot")),
(("Fjalë"), ("Word")),
(("Por"), ("But")),
(("Çfarë"), ("What")),
(("Disa"), ("Some")),
(("Është"), ("Is")),
(("Ajo"), ("It")),
(("Ju"), ("You")),
(("Ose"), ("Or")),
(("Kishte"), ("Had")),
(("Thonë"), ("The")),
(("I"), ("Of")),
(("Në"), ("To")),
(("Dhe"), ("And")),
(("Një"), ("A")),
(("Në"), ("In")),
(("Ne"), ("We")),
(("Mund"), ("Can")),
(("Jashtë"), ("Out")),
(("Tjetër"), ("Other")),
(("Ishin"), ("Were")),
(("E Cila"), ("Which")),
(("Bëj"), ("Do")),
(("Tyre"), ("Their")),
(("Koha"), ("Time")),
(("Nëse"), ("If")),
(("Do"), ("Will")),
(("Si"), ("How")),
(("Tha"), ("Said")),
(("Një"), ("An")),
(("Çdo"), ("Each")),
(("Them"), ("Tell")),
(("Bën"), ("Does")),
(("I Vendosur"), ("Set")),
(("Tre"), ("Three")),
(("Dua"), ("Want")),
(("Ajrit"), ("Air")),
(("Mirë"), ("Well")),
(("Edhe"), ("Also")),
(("Luajnë"), ("Play")),
(("Vogël"), ("Small")),
(("Fund"), ("End")),
(("Vendos"), ("Put")),
(("Shtëpi"), ("Home")),
(("Lexoj"), ("Read")),
(("Dorë"), ("Hand")),
(("Port"), ("Port")),
(("I Madh"), ("Large")),
(("Magji"), ("Spell")),
(("Të Shtoni"), ("Add")),
(("Edhe"), ("Even")),
(("Tokë"), ("Land")),
(("Këtu"), ("Here")),
(("Duhet"), ("Must")),
(("I Madh"), ("Big")),
(("I Lartë"), ("High")),
(("I Tillë"), ("Such")),
(("Ndjek"), ("Follow")),
(("Akt"), ("Act")),
(("Pse"), ("Why")),
(("Kërkoj"), ("Ask")),
(("Burra"), ("Men")),
(("Ndryshim"), ("Change")),
(("Shkoi"), ("Went")),
(("Dritë"), ("Light")),
(("Lloj"), ("Kind")),
(("Nga"), ("Off")),
(("Duhet"), ("Need")),
(("Shtëpi"), ("House")),
(("Foto"), ("Picture")),
(("Përpiqem"), ("Try")),
(("Na"), ("Us")),
(("Përsëri"), ("Again")),
(("Kafshëve"), ("Animal")),
(("Pikë"), ("Point")),
(("Nënë"), ("Mother")),
(("Botëror"), ("World")),
(("Afër"), ("Near")),
(("Ndërtuar"), ("Build")),
(("Vetë"), ("Self")),
(("Toka"), ("Earth")),
(("Baba"), ("Father")),
(("Ndonjë"), ("Any")),
(("Të Reja"), ("New")),
(("Punë"), ("Work")),
(("Pjesë"), ("Part")),
(("Marrë"), ("Take")),
(("Marrë"), ("Get")),
(("Vendi"), ("Place")),
(("Bërë"), ("Made")),
(("Jetojnë"), ("Live")),
(("Ku"), ("Where")),
(("Pas"), ("After")),
(("Mbrapa"), ("Back")),
(("Pak"), ("Little")),
(("Vetëm"), ("Only")),
(("Rreth"), ("Round")),
(("Njeri"), ("Man")),
(("Vit"), ("Year")),
(("Erdhi"), ("Came")),
(("Show"), ("Show")),
(("Çdo"), ("Every")),
(("Mirë"), ("Good")),
(("Mua"), ("Me")),
(("Jap"), ("Give")),
(("Tonë"), ("Our")),
(("Nën"), ("Under")),
(("Emri"), ("Name")),
(("Shumë"), ("Very")),
(("Me Anë Të"), ("Through")),
(("Vetëm"), ("Just")),
(("Formë"), ("Form")),
(("Fjali"), ("Sentence")),
(("I Madh"), ("Great")),
(("Mendoj"), ("Think")),
(("Thonë"), ("Say")),
(("Të Ndihmojë"), ("Help")),
(("Ulët"), ("Low")),
(("Linjë"), ("Line")),
(("Ndryshoj"), ("Differ")),
(("Kthesë"), ("Turn")),
(("Shkaku"), ("Cause")),
(("Shumë"), ("Much")),
(("Mesatare"), ("Mean")),
(("Para"), ("Before")),
(("Veprim"), ("Move")),
(("Drejtë"), ("Right")),
(("Djalë"), ("Boy")),
(("Vjetër"), ("Old")),
(("Shumë"), ("Too")),
(("I Njëjtë"), ("Same")),
(("Ajo"), ("She")),
(("Të Gjithë"), ("All")),
(("Atje"), ("There")),
(("Kur"), ("When")),
(("Up"), ("Up")),
(("Përdorimi"), ("Use")),
(("Tuaj"), ("Your")),
(("Mënyrë"), ("Way")),
(("Për"), ("About")),
(("Shumë"), ("Many")),
(("Pastaj"), ("Then")),
(("Ata"), ("Them")),
(("Shkruaj"), ("Write")),
(("Do"), ("Would")),
(("Si"), ("Like")),
(("Kështu"), ("So")),
(("Këto"), ("These")),
(("E Saj"), ("Her")),
(("Gjatë"), ("Long")),
(("Bëj"), ("Make")),
(("Gjë"), ("Thing")),
(("Shih"), ("See")),
(("Atë"), ("Him")),
(("Dy"), ("Two")),
(("Ka"), ("Has")),
(("Shikoni"), ("Look")),
(("Më Shumë"), ("More")),
(("Ditë"), ("Day")),
(("Mund"), ("Could")),
(("Shkoj"), ("Go")),
(("Eja"), ("Come")),
(("Bëri"), ("Did")),
(("Numri"), ("Number")),
(("Zë"), ("Sound")),
(("Asnjë"), ("No")),
(("Më"), ("Most")),
(("Njerëz"), ("People")),
(("Tim"), ("My")),
(("Mbi"), ("Over")),
(("Di"), ("Know")),
(("Ujë"), ("Water")),
(("Se"), ("Than")),
(("Thirrje"), ("Call")),
(("Parë"), ("First")),
(("Që"), ("Who")),
(("Mund"), ("May")),
(("Poshtë"), ("Down")),
(("Anë"), ("Side")),
(("Qenë"), ("Been")),
(("Tani"), ("Now")),
(("Gjeni"), ("Find")),
(("Kreu"), ("Head")),
(("Qëndrim"), ("Stand")),
(("Vet"), ("Own")),
(("Faqe"), ("Page")),
(("Duhet"), ("Should")),
(("Vendi"), ("Country")),
(("Gjetur"), ("Found")),
(("Përgjigje"), ("Answer")),
(("Shkollë"), ("School")),
(("Rritet"), ("Grow")),
(("Studimi"), ("Study")),
(("Ende"), ("Still")),
(("Mësoj"), ("Learn")),
(("Bimë"), ("Plant")),
(("Mbuluar"), ("Cover")),
(("Ushqim"), ("Food")),
(("Dielli"), ("Sun")),
(("Katër"), ("Four")),
(("Në Mes Të"), ("Between")),
(("Shtet"), ("State")),
(("Mbaj"), ("Keep")),
(("Sy"), ("Eye")),
(("Kurrë"), ("Never")),
(("Fundit"), ("Last")),
(("Le Të"), ("Let")),
(("Mendimi"), ("Thought")),
(("Qytet"), ("City")),
(("Pemë"), ("Tree")),
(("Kalojnë"), ("Cross")),
(("Fermë"), ("Farm")),
(("Vështirë"), ("Hard")),
(("Fillimi"), ("Start")),
(("Mund"), ("Might")),
(("Histori"), ("Story")),
(("Pa"), ("Saw")),
(("Tani"), ("Far")),
(("Deti"), ("Sea")),
(("Barazim"), ("Draw")),
(("La"), ("Left")),
(("Vonë"), ("Late")),
(("Drejtuar"), ("Run")),
(("Nuk"), ("Don’T")),
(("Ndërsa"), ("While")),
(("Shtypi"), ("Press")),
(("Afër"), ("Close")),
(("Natën"), ("Night")),
(("Real"), ("Real")),
(("Jetë"), ("Life")),
(("Pak"), ("Few")),
(("Veri"), ("North")),
(("Libri"), ("Book")),
(("Kryer"), ("Carry")),
(("Mori"), ("Took")),
(("Shkenca"), ("Science")),
(("Hani"), ("Eat")),
(("Dhomë"), ("Room")),
(("Mik"), ("Friend")),
(("Filloi"), ("Began")),
(("Ideja"), ("Idea")),
(("Peshk"), ("Fish")),
(("Mal"), ("Mountain")),
(("Stop"), ("Stop")),
(("Dikur"), ("Once")),
(("Bazë"), ("Base")),
(("Dëgjojë"), ("Hear")),
(("Kalë"), ("Horse")),
(("Prerë"), ("Cut")),
(("I Sigurt"), ("Sure")),
(("Shikojnë"), ("Watch")),
(("Ngjyra"), ("Color")),
(("Fytyrë"), ("Face")),
(("Dru"), ("Wood")),
(("Kryesore"), ("Main")),
(("Hapur"), ("Open")),
(("Duket"), ("Seem")),
(("Së Bashku"), ("Together")),
(("Tjetër"), ("Next")),
(("E Bardhë"), ("White")),
(("Fëmijë"), ("Children")),
(("Të Fillojë"), ("Begin")),
(("Mori"), ("Got")),
(("Eci"), ("Walk")),
(("Shembull"), ("Example")),
(("Lehtësuar"), ("Ease")),
(("Letër"), ("Paper")),
(("Grup"), ("Group")),
(("Gjithmonë"), ("Always")),
(("Muzikë"), ("Music")),
(("Ato"), ("Those")),
(("Të Dy"), ("Both")),
(("Mark"), ("Mark")),
(("Shpesh"), ("Often")),
(("Letër"), ("Letter")),
(("Deri"), ("Until")),
(("Milje"), ("Mile")),
(("Lumi"), ("River")),
(("Makinë"), ("Car")),
(("Këmbët"), ("Feet")),
(("Kujdes"), ("Care")),
(("I Dytë"), ("Second")),
(("Mjaft"), ("Enough")),
(("Plain"), ("Plain")),
(("Vajzë"), ("Girl")),
(("Zakonshme"), ("Usual")),
(("I Ri"), ("Young")),
(("Gati"), ("Ready")),
(("Sipër"), ("Above")),
(("Kurrë"), ("Ever")),
(("I Kuq"), ("Red")),
(("Lista"), ("List")),
(("Ndonëse"), ("Though")),
(("Të Ndjehen Të"), ("Feel")),
(("Flasim"), ("Talk")),
(("Zog"), ("Bird")),
(("Shpejt"), ("Soon")),
(("Trupi"), ("Body")),
(("Qen"), ("Dog")),
(("Familja"), ("Family")),
(("Drejtpërdrejtë"), ("Direct")),
(("Paraqesin"), ("Pose")),
(("Largohen"), ("Leave")),
(("Song"), ("Song")),
(("Të Matur"), ("Measure")),
(("Dyer"), ("Door")),
(("Produkt"), ("Product")),
(("E Zezë"), ("Black")),
(("I Shkurtër"), ("Short")),
(("Numëror"), ("Numeral")),
(("Klasë"), ("Class")),
(("Era"), ("Wind")),
(("Pyetje"), ("Question")),
(("Ndodhë"), ("Happen")),
(("I Plotë"), ("Complete")),
(("Anije"), ("Ship")),
(("Zonë"), ("Area")),
(("Gjysmë"), ("Half")),
(("Shkëmb"), ("Rock")),
(("Mënyrë"), ("Order")),
(("Zjarri"), ("Fire")),
(("Jug"), ("South")),
(("Problemi"), ("Problem")),
(("Pjesë"), ("Piece")),
(("Tha"), ("Told")),
(("Dinte"), ("Knew")),
(("Kaloj"), ("Pass")),
(("Që Prej"), ("Since")),
(("Top"), ("Top")),
(("Tërë"), ("Whole")),
(("Mbreti"), ("King")),
(("Rrugë"), ("Street")),
(("Inç"), ("Inch")),
(("Shumohen"), ("Multiply")),
(("Asgjë"), ("Nothing")),
(("Sigurisht"), ("Course")),
(("Qëndrojnë"), ("Stay")),
(("Rrotë"), ("Wheel")),
(("Plotë"), ("Full")),
(("Forca"), ("Force")),
(("Blu"), ("Blue")),
(("Objekt"), ("Object")),
(("Vendosë"), ("Decide")),
(("Sipërfaqe"), ("Surface")),
(("Thellë"), ("Deep")),
(("Moon"), ("Moon")),
(("Ishull"), ("Island")),
(("Këmbë"), ("Foot")),
(("Sistemi"), ("System")),
(("I Zënë"), ("Busy")),
(("Provë"), ("Test")),
(("Rekord"), ("Record")),
(("Varkë"), ("Boat")),
(("Përbashkët"), ("Common")),
(("Ari"), ("Gold")),
(("Të Jetë E Mundur"), ("Possible")),
(("Aeroplan"), ("Plane")),
(("Në Vend"), ("Stead")),
(("Thatë"), ("Dry")),
(("Pyes Veten"), ("Wonder")),
(("Qesh"), ("Laugh")),
(("Mijë"), ("Thousand")),
(("Më Parë"), ("Ago")),
(("Vrapoi"), ("Ran")),
(("Kontrolloj"), ("Check")),
(("Lojë"), ("Game")),
(("Formë"), ("Shape")),
(("Barazojnë"), ("Equate")),
(("Hot"), ("Hot")),
(("Miss"), ("Miss")),
(("Solli"), ("Brought")),
(("Ngrohjes"), ("Heat")),
(("Borë"), ("Snow")),
(("Gomë"), ("Tire")),
(("Sjellë"), ("Bring")),
(("Po"), ("Yes")),
(("I Largët"), ("Distant")),
(("Mbushur"), ("Fill")),
(("Lindje"), ("East")),
(("Bojë"), ("Paint")),
(("Gjuha"), ("Language")),
(("Në Mesin E"), ("Among")),
(("Njësi"), ("Unit")),
(("Fuqia"), ("Power")),
(("Qytet"), ("Town")),
(("Gjobë"), ("Fine")),
(("Sigurt"), ("Certain")),
(("Fluturojnë"), ("Fly")),
(("Bien"), ("Fall")),
(("Të Çojë"), ("Lead")),
(("Qaj"), ("Cry")),
(("Errët"), ("Dark")),
(("Makinë"), ("Machine")),
(("Shënim"), ("Note")),
(("Pres"), ("Wait")),
(("Plani"), ("Plan")),
(("Shifër"), ("Figure")),
(("Yll"), ("Star")),
(("Kuti"), ("Box")),
(("Emër"), ("Noun")),
(("Fushë"), ("Field")),
(("Tjetër"), ("Rest")),
(("Saktë"), ("Correct")),
(("Gjendje"), ("Able")),
(("Kile"), ("Pound")),
(("E Bërë"), ("Done")),
(("Bukuri"), ("Beauty")),
(("Makinë"), ("Drive")),
(("Qëndroi"), ("Stood")),
(("Përmbaj"), ("Contain")),
(("Para"), ("Front")),
(("Mësojnë"), ("Teach")),
(("Javë"), ("Week")),
(("Përfundimtar"), ("Final")),
(("Dha"), ("Gave")),
(("E Gjelbër"), ("Green")),
(("Oh"), ("Oh")),
(("Shpejtë"), ("Quick")),
(("Zhvilloj"), ("Develop")),
(("Oqean"), ("Ocean")),
(("Ngrohtë"), ("Warm")),
(("Pa Pagesë"), ("Free")),
(("Minutë"), ("Minute")),
(("Fortë"), ("Strong")),
(("Të Veçantë"), ("Special")),
(("Mendja"), ("Mind")),
(("Prapa"), ("Behind")),
(("Qartë"), ("Clear")),
(("Bisht"), ("Tail")),
(("Prodhojnë"), ("Produce")),
(("Fakti"), ("Fact")),
(("Hapësirë"), ("Space")),
(("Dëgjuar"), ("Heard")),
(("Mirë"), ("Best")),
(("Orë"), ("Hour")),
(("Më Mirë"), ("Better")),
(("E Vërtetë"), ("True")),
(("Gjatë"), ("During")),
(("Njëqind"), ("Hundred")),
(("Pesë"), ("Five")),
(("Kujtoj"), ("Remember")),
(("Hapi"), ("Step")),
(("Fillim"), ("Early")),
(("Mbajë"), ("Hold")),
(("Perëndim"), ("West")),
(("Terren"), ("Ground")),
(("Interesi"), ("Interest")),
(("Arrijnë"), ("Reach")),
(("Shpejtë"), ("Fast")),
(("Folje"), ("Verb")),
(("Këndoj"), ("Sing")),
(("Dëgjoni"), ("Listen")),
(("Gjashtë"), ("Six")),
(("Tabela"), ("Table")),
(("Udhëtimit"), ("Travel")),
(("Më Pak"), ("Less")),
(("Mëngjes"), ("Morning")),
(("Dhjetë"), ("Ten")),
(("Thjeshtë"), ("Simple")),
(("Disa"), ("Several")),
(("Zanore"), ("Vowel")),
(("Drejt"), ("Toward")),
(("Luftë"), ("War")),
(("Vë"), ("Lay")),
(("Kundër"), ("Against")),
(("Model"), ("Pattern")),
(("I Ngadalshëm"), ("Slow")),
(("Qendër"), ("Center")),
(("Dashuri"), ("Love")),
(("Person"), ("Person")),
(("Paratë"), ("Money")),
(("Shërbejnë"), ("Serve")),
(("Duket"), ("Appear")),
(("Rrugë"), ("Road")),
(("Harta"), ("Map")),
(("Shi"), ("Rain")),
(("Rregull"), ("Rule")),
(("Qeverisur"), ("Govern")),
(("Tërheq"), ("Pull")),
(("Ftohtë"), ("Cold")),
(("Njoftim"), ("Notice")),
(("Zë"), ("Voice")),
(("Energjisë"), ("Energy")),
(("Gjueti"), ("Hunt")),
(("Mundshme"), ("Probable")),
(("Krevat"), ("Bed")),
(("Vëlla"), ("Brother")),
(("Vezë"), ("Egg")),
(("Udhëtim"), ("Ride")),
(("Qelizë"), ("Cell")),
(("Besoj"), ("Believe")),
(("Ndoshta"), ("Perhaps")),
(("Marr"), ("Pick")),
(("Papritur"), ("Sudden")),
(("Të Llogarisë"), ("Count")),
(("Katrore"), ("Square")),
(("Arsyeja"), ("Reason")),
(("Gjatësia"), ("Length")),
(("Përfaqësojnë"), ("Represent")),
(("Art"), ("Art")),
(("Subjekt"), ("Subject")),
(("Rajoni"), ("Region")),
(("Madhësia"), ("Size")),
(("Ndryshojnë"), ("Vary")),
(("Vendosen"), ("Settle")),
(("Flasin"), ("Speak")),
(("Pesha"), ("Weight")),
(("Përgjithshme"), ("General")),
(("Akull"), ("Ice")),
(("Çështje"), ("Matter")),
(("Rrethi"), ("Circle")),
(("Palë"), ("Pair")),
(("Përfshijnë"), ("Include")),
(("Ndarje"), ("Divide")),
(("Rrokje"), ("Syllable")),
(("Ndjerë"), ("Felt")),
(("I Madh"), ("Grand")),
(("Top"), ("Ball")),
(("Ende"), ("Yet")),
(("Vala"), ("Wave")),
(("Rënie"), ("Drop")),
(("Zemra"), ("Heart")),
(("Jam"), ("Am")),
(("Pranishëm"), ("Present")),
(("Rëndë"), ("Heavy")),
(("Valle"), ("Dance")),
(("Motor"), ("Engine")),
(("Pozita"), ("Position")),
(("Krah"), ("Arm")),
(("Të Gjerë"), ("Wide")),
(("Lundrojnë"), ("Sail")),
(("Material"), ("Material")),
(("Fraksion"), ("Fraction")),
(("Pyjeve"), ("Forest")),
(("Rri"), ("Sit")),
(("Garë"), ("Race")),
(("Dritare"), ("Window")),
(("Dyqan"), ("Store")),
(("Verë"), ("Summer")),
(("Tren"), ("Train")),
(("Gjumë"), ("Sleep")),
(("Provoj"), ("Prove")),
(("I Vetëm"), ("Lone")),
(("Këmbë"), ("Leg")),
(("Ushtrim"), ("Exercise")),
(("Mur"), ("Wall")),
(("Kapur"), ("Catch")),
(("Mali"), ("Mount")),
(("Uroj"), ("Wish")),
(("Qiell"), ("Sky")),
(("Bordi"), ("Board")),
(("Lumturi"), ("Joy")),
(("Dimrit"), ("Winter")),
(("Sat"), ("Sat")),
(("Shkruar"), ("Written")),
(("Egra"), ("Wild")),
(("Instrument"), ("Instrument")),
(("Mbajtur"), ("Kept")),
(("Qelqi"), ("Glass")),
(("Bari"), ("Grass")),
(("Lopë"), ("Cow")),
(("Punë"), ("Job")),
(("Edge"), ("Edge")),
(("Shenjë"), ("Sign")),
(("Vizitë"), ("Visit")),
(("E Kaluara"), ("Past")),
(("E Butë"), ("Soft")),
(("Argëtim"), ("Fun")),
(("Ndritshme"), ("Bright")),
(("Gazit"), ("Gas")),
(("Mot"), ("Weather")),
(("Muaj"), ("Month")),
(("Milion"), ("Million")),
(("Mbajnë"), ("Bear")),
(("Finish"), ("Finish")),
(("Të Lumtur"), ("Happy")),
(("Shpresoj"), ("Hope")),
(("Lule"), ("Flower")),
(("Vesh"), ("Clothe")),
(("Çuditshme"), ("Strange")),
(("Shkuar"), ("Gone")),
(("Tregtisë"), ("Trade")),
(("Melodi"), ("Melody")),
(("Udhëtim"), ("Trip")),
(("Zyrë"), ("Office")),
(("Marrë"), ("Receive")),
(("Rresht"), ("Row")),
(("Gojë"), ("Mouth")),
(("Saktë"), ("Exact")),
(("Simbol"), ("Symbol")),
(("Vdes"), ("Die")),
(("Më Pak"), ("Least")),
(("Probleme"), ("Trouble")),
(("Bërtas"), ("Shout")),
(("Me Përjashtim Të"), ("Except")),
(("Shkroi"), ("Wrote")),
(("Farë"), ("Seed")),
(("Ton"), ("Tone")),
(("Bashkohen"), ("Join")),
(("Sugjerojnë"), ("Suggest")),
(("I Pastër"), ("Clean")),
(("Pushim"), ("Break")),
(("Lady"), ("Lady")),
(("Oborr"), ("Yard")),
(("Ngrihem"), ("Rise")),
(("Keq"), ("Bad")),
(("Goditje"), ("Blow")),
(("Naftës"), ("Oil")),
(("Gjak"), ("Blood")),
(("Prek"), ("Touch")),
(("U Rrit"), ("Grew")),
(("Cent"), ("Cent")),
(("Përzierje"), ("Mix")),
(("Ekipi"), ("Team")),
(("Tela"), ("Wire")),
(("Kosto"), ("Cost")),
(("Humbur"), ("Lost")),
(("Kafe"), ("Brown")),
(("Vesh"), ("Wear")),
(("Kopsht"), ("Garden")),
(("Barabartë"), ("Equal")),
(("Dërguar"), ("Sent")),
(("Zgjidhni"), ("Choose")),
(("Ra"), ("Fell")),
(("Përshtaten"), ("Fit")),
(("Rrjedhë"), ("Flow")),
(("Drejtë"), ("Fair")),
(("Banka"), ("Bank")),
(("Mbledhë"), ("Collect")),
(("Ruani"), ("Save")),
(("Kontrollit"), ("Control")),
(("Dhjetor"), ("Decimal")),
(("Vesh"), ("Ear")),
(("Tjetër"), ("Else")),
(("Mjaft"), ("Quite")),
(("Thyen"), ("Broke")),
(("Rasti"), ("Case")),
(("Mesme"), ("Middle")),
(("Vrasin"), ("Kill")),
(("Djali"), ("Son")),
(("Liqeni"), ("Lake")),
(("Moment"), ("Moment")),
(("Shkallë"), ("Scale")),
(("Me Zë Të Lartë"), ("Loud")),
(("Pranverë"), ("Spring")),
(("Vëzhguar"), ("Observe")),
(("Fëmijë"), ("Child")),
(("Drejt"), ("Straight")),
(("Bashkëtingëllore"), ("Consonant")),
(("Komb"), ("Nation")),
(("Fjalor"), ("Dictionary")),
(("Qumësht"), ("Milk")),
(("Shpejtësi"), ("Speed")),
(("Metoda"), ("Method")),
(("Organ"), ("Organ")),
(("Paguajnë"), ("Pay")),
(("Mosha"), ("Age")),
(("Seksion"), ("Section")),
(("Veshje"), ("Dress")),
(("Cloud"), ("Cloud")),
(("Surprizë"), ("Surprise")),
(("I Qetë"), ("Quiet")),
(("Guri"), ("Stone")),
(("Vogël"), ("Tiny")),
(("Ngjit"), ("Climb")),
(("I Ftohtë"), ("Cool")),
(("Dizajn"), ("Design")),
(("Varfër"), ("Poor")),
(("Shumë"), ("Lot")),
(("Eksperiment"), ("Experiment")),
(("Fund"), ("Bottom")),
(("Kyç"), ("Key")),
(("Hekuri"), ("Iron")),
(("I Vetëm"), ("Single")),
(("Shkop"), ("Stick")),
(("Banesë"), ("Flat")),
(("Njëzet"), ("Twenty")),
(("Lëkurës"), ("Skin")),
(("Buzëqeshje"), ("Smile")),
(("Rrudhë"), ("Crease")),
(("Vrimë"), ("Hole")),
(("Kërcejnë"), ("Jump")),
(("Fëmijë"), ("Baby")),
(("Tetë"), ("Eight")),
(("Fshati"), ("Village")),
(("Takohen"), ("Meet")),
(("Rrënjë"), ("Root")),
(("Blej"), ("Buy")),
(("Të Rritur"), ("Raise")),
(("Zgjidhur"), ("Solve")),
(("Metalike"), ("Metal")),
(("Nëse"), ("Whether")),
(("Shtytje"), ("Push")),
(("Shtatë"), ("Seven")),
(("Paragraf"), ("Paragraph")),
(("Tretë"), ("Third")),
(("Duhet"), ("Shall")),
(("Mbajtur"), ("Held")),
(("Flokët"), ("Hair")),
(("Përshkruajnë"), ("Describe")),
(("Kuzhinier"), ("Cook")),
(("Kati"), ("Floor")),
(("Ose"), ("Either")),
(("Rezultati"), ("Result")),
(("Djeg"), ("Burn")),
(("Kodër"), ("Hill")),
(("I Sigurt"), ("Safe")),
(("Mace"), ("Cat")),
(("Shekulli"), ("Century")),
(("Konsiderojnë"), ("Consider")),
(("Lloj"), ("Type")),
(("Ligji"), ("Law")),
(("Bit"), ("Bit")),
(("Bregdeti"), ("Coast")),
(("Kopje"), ("Copy")),
(("Fraza"), ("Phrase")),
(("Heshtur"), ("Silent")),
(("I Gjatë"), ("Tall")),
(("Rërë"), ("Sand")),
(("Tokës"), ("Soil")),
(("Roll"), ("Roll")),
(("Temperatura"), ("Temperature")),
(("Gisht"), ("Finger")),
(("Industri"), ("Industry")),
(("Vlera"), ("Value")),
(("Lufta"), ("Fight")),
(("Gënjeshtër"), ("Lie")),
(("Rrah"), ("Beat")),
(("Nxeh"), ("Excite")),
(("Natyrore"), ("Natural")),
(("View"), ("View")),
(("Kuptim"), ("Sense")),
(("Kapitalit"), ("Capital")),
(("Nuk Do Të"), ("Won’T")),
(("Karrige"), ("Chair")),
(("Rrezik"), ("Danger")),
(("Fruta"), ("Fruit")),
(("I Pasur"), ("Rich")),
(("I Trashë"), ("Thick")),
(("Ushtar"), ("Soldier")),
(("Procesi"), ("Process")),
(("Operoj"), ("Operate")),
(("Praktikë"), ("Practice")),
(("Të Ndara"), ("Separate")),
(("I Vështirë"), ("Difficult")),
(("Mjeku"), ("Doctor")),
(("Ju Lutem"), ("Please")),
(("Mbrojtur"), ("Protect")),
(("Mesditë"), ("Noon")),
(("Kulture"), ("Crop")),
(("Moderne"), ("Modern")),
(("Element"), ("Element")),
(("Hit"), ("Hit")),
(("Studenti"), ("Student")),
(("Qoshe"), ("Corner")),
(("Parti"), ("Party")),
(("Furnizim"), ("Supply")),
(("Të Cilit"), ("Whose")),
(("Gjetur"), ("Locate")),
(("Unazë"), ("Ring")),
(("Karakter"), ("Character")),
(("Insekteve"), ("Insect")),
(("Kapur"), ("Caught")),
(("Periudha"), ("Period")),
(("Tregojnë"), ("Indicate")),
(("Radio"), ("Radio")),
(("Foli"), ("Spoke")),
(("Atom"), ("Atom")),
(("Njerëzore"), ("Human")),
(("Historia"), ("History")),
(("Efekti"), ("Effect")),
(("Elektrike"), ("Electric")),
(("Presin"), ("Expect")),
(("Kockave"), ("Bone")),
(("Hekurudhor"), ("Rail")),
(("Imagjinoni"), ("Imagine")),
(("Sigurojë"), ("Provide")),
(("Pajtohem"), ("Agree")),
(("Kështu"), ("Thus")),
(("I Butë"), ("Gentle")),
(("Grua"), ("Woman")),
(("Kapiten"), ("Captain")),
(("Guess"), ("Guess")),
(("Nevojshme"), ("Necessary")),
(("Mprehtë"), ("Sharp")),
(("Krahut"), ("Wing")),
(("Krijuar"), ("Create")),
(("Fqinji"), ("Neighbor")),
(("Laj"), ("Wash")),
(("Lakuriq Nate"), ("Bat")),
(("Më Tepër"), ("Rather")),
(("Turmë"), ("Crowd")),
(("Misri"), ("Corn")),
(("Të Krahasuar"), ("Compare")),
(("Poemë"), ("Poem")),
(("String"), ("String")),
(("Zile"), ("Bell")),
(("Varet"), ("Depend")),
(("Mish"), ("Meat")),
(("Fshij"), ("Rub")),
(("Tub"), ("Tube")),
(("I Famshëm"), ("Famous")),
(("Dollar"), ("Dollar")),
(("Lumë"), ("Stream")),
(("Frikë"), ("Fear")),
(("Pamje"), ("Sight")),
(("I Hollë"), ("Thin")),
(("Trekëndësh"), ("Triangle")),
(("Planet"), ("Planet")),
(("Nxitim"), ("Hurry")),
(("Shefi"), ("Chief")),
(("Koloni"), ("Colony")),
(("Ora"), ("Clock")),
(("Minave"), ("Mine")),
(("Kravatë"), ("Tie")),
(("Hyjnë"), ("Enter")),
(("I Madh"), ("Major")),
(("Freskët"), ("Fresh")),
(("Kërko"), ("Search")),
(("Dërgoni"), ("Send")),
(("Verdhë"), ("Yellow")),
(("Armë"), ("Gun")),
(("Lejojnë"), ("Allow")),
(("Print"), ("Print")),
(("Vdekur"), ("Dead")),
(("Vend"), ("Spot")),
(("Shkretëtirë"), ("Desert")),
(("Kostum"), ("Suit")),
(("Aktuale"), ("Current")),
(("Ashensor"), ("Lift")),
(("U Rrit"), ("Rose")),
(("Arrijnë"), ("Arrive")),
(("Mjeshtër"), ("Master")),
(("Udhë"), ("Track")),
(("Prind"), ("Parent")),
(("Breg"), ("Shore")),
(("Ndarje"), ("Division")),
(("Fletë"), ("Sheet")),
(("Substancë"), ("Substance")),
(("Favor"), ("Favor")),
(("Lidhur"), ("Connect")),
(("Pas"), ("Post")),
(("Shpenzojnë"), ("Spend")),
(("Akord"), ("Chord")),
(("Yndyrë"), ("Fat")),
(("Kënaqur"), ("Glad")),
(("Origjinal"), ("Original")),
(("Pjesa"), ("Share")),
(("Stacion"), ("Station")),
(("Baba"), ("Dad")),
(("Bukë"), ("Bread")),
(("Ngarkuar"), ("Charge")),
(("I Duhur"), ("Proper")),
(("Bar"), ("Bar")),
(("Oferta"), ("Offer")),
(("Segment"), ("Segment")),
(("Rob"), ("Slave")),
(("Duck"), ("Duck")),
(("I Menjëhershëm"), ("Instant")),
(("Tregu"), ("Market")),
(("Shkallë"), ("Degree")),
(("Populloj"), ("Populate")),
(("Zogth"), ("Chick")),
(("I Dashur"), ("Dear")),
(("Armik"), ("Enemy")),
(("Përgjigjen"), ("Reply")),
(("Pije"), ("Drink")),
(("Ndodhin"), ("Occur")),
(("Mbështetje"), ("Support")),
(("Fjalim"), ("Speech")),
(("Natyra"), ("Nature")),
(("Varg"), ("Range")),
(("Avull"), ("Steam")),
(("Lëvizje"), ("Motion")),
(("Rrugë"), ("Path")),
(("Lëngshme"), ("Liquid")),
(("Log"), ("Log")),
(("Do Të Thoshte"), ("Meant")),
(("Herës"), ("Quotient")),
(("Dhëmbët"), ("Teeth")),
(("Shell"), ("Shell")),
(("Qafë"), ("Neck")),
(("Oksigjen"), ("Oxygen")),
(("Sheqer"), ("Sugar")),
(("Vdekja"), ("Death")),
(("Mjaft"), ("Pretty")),
(("Aftësi"), ("Skill")),
(("Gratë"), ("Women")),
(("Sezon"), ("Season")),
(("Zgjidhje"), ("Solution")),
(("Magnet"), ("Magnet")),
(("Argjendi"), ("Silver")),
(("Thank"), ("Thank")),
(("Degë"), ("Branch")),
(("Ndeshje"), ("Match")),
(("Prapashtesë"), ("Suffix")),
(("Sidomos"), ("Especially")),
(("Fiku"), ("Fig")),
(("I Frikësuar"), ("Afraid")),
(("I Madh"), ("Huge")),
(("Motra"), ("Sister")),
(("Çeliku"), ("Steel")),
(("Diskutuar"), ("Discuss")),
(("Përpara"), ("Forward")),
(("Ngjashme"), ("Similar")),
(("Udhëzojë"), ("Guide")),
(("Përvojë"), ("Experience")),
(("Pikë"), ("Score")),
(("Mollë"), ("Apple")),
(("Blerë"), ("Bought")),
(("Udhëhequr"), ("Led")),
(("Katran"), ("Pitch")),
(("Pallto"), ("Coat")),
(("Në Masë"), ("Mass")),
(("Kartë"), ("Card")),
(("Band"), ("Band")),
(("Litar"), ("Rope")),
(("Shqip"), ("Slip")),
(("Fitore"), ("Win")),
(("Ëndërr"), ("Dream")),
(("Mbrëmje"), ("Evening")),
(("Kusht"), ("Condition")),
(("Ushqim"), ("Feed")),
(("Mjet"), ("Tool")),
(("Totale"), ("Total")),
(("Themelore"), ("Basic")),
(("Erë"), ("Smell")),
(("Luginë"), ("Valley")),
(("As"), ("Nor")),
(("Dyfishtë"), ("Double")),
(("Vend"), ("Seat")),
(("Vazhdojnë"), ("Continue")),
(("Bllok"), ("Block")),
(("Tabelë"), ("Chart")),
(("Hat"), ("Hat")),
(("Shes"), ("Sell")),
(("Suksesi"), ("Success")),
(("Kompania"), ("Company")),
(("Zbres"), ("Subtract")),
(("Ngjarje"), ("Event")),
(("I Veçantë"), ("Particular")),
(("Marrëveshje"), ("Deal")),
(("Notoj"), ("Swim")),
(("Term"), ("Term")),
(("Kundërta"), ("Opposite")),
(("Gruaja"), ("Wife")),
(("Këpucëve"), ("Shoe")),
(("Shpatull"), ("Shoulder")),
(("Përhap"), ("Spread")),
(("Organizoni"), ("Arrange")),
(("Kampi"), ("Camp")),
(("Trillime"), ("Invent")),
(("Pambuku"), ("Cotton")),
(("Born"), ("Born")),
(("Përcaktuar"), ("Determine")),
(("Kuart"), ("Quart")),
(("Nëntë"), ("Nine")),
(("Kamion"), ("Truck")),
(("Zhurmë"), ("Noise")),
(("Nivel"), ("Level")),
(("Shans"), ("Chance")),
(("Mblidhen"), ("Gather")),
(("Dyqan"), ("Shop")),
(("Shtrirje"), ("Stretch")),
(("Hedh"), ("Throw")),
(("Shndrit"), ("Shine")),
(("Pronë"), ("Property")),
(("Kolona"), ("Column")),
(("Molekulë"), ("Molecule")),
(("Zgjidhni"), ("Select")),
(("Gabuar"), ("Wrong")),
(("Gri"), ("Gray")),
(("Përsëritje"), ("Repeat")),
(("Kërkojnë"), ("Require")),
(("Gjerë"), ("Broad")),
(("Përgatisë"), ("Prepare")),
(("Kripë"), ("Salt")),
(("Hundë"), ("Nose")),
(("Shumës"), ("Plural")),
(("Zemërimi"), ("Anger")),
(("Pretendim"), ("Claim")),
(("Kontinenti"), ("Continent")),]

# %%
# Length of Words List

count = len(words)

# %%
# Define a function to create a random word

def next():
    global hinter, hint_count
    '''Clear the screen'''
    answer_label.config(text="")
    my_entry.delete(0, END)
    hint_label.config(text = "")
    # Reset hint
    hinter = ""
    hint_count = 0
    
    '''Create a global variable as a random selection'''
    global random_word
    random_word = randint(0, count-1)
    '''Update the label with a Shqip word'''
    shqip_word.config(text=words[random_word][0])
    

# %%
# Define a function to create a random word

def answer():
    if my_entry.get().capitalize() == words[random_word][1]:
        answer_label.config(text=f"Correct! {words[random_word][0]} is {words[random_word][1]}")
    else:
        answer_label.config(text=f"Incorrect! {words[random_word][0]} is not {my_entry.get().capitalize()}")

# %%
# Define a function to give a hint

hinter = ""
hint_count = 0

def hint():
    global hint_count
    global hinter

    if hint_count < len(words[random_word][1]):
        hinter = hinter + words[random_word][1][hint_count]
        hint_label.config(text = hinter)
        hint_count += 1


# %%
# Get a count of the word list

shqip_word = Label(root, text="", font=("TW Cen MT", 50))
shqip_word.pack(pady=50)

answer_label = Label(root, text="")
answer_label.pack(pady=20)

info = StringVar()
my_entry = Entry(root, textvariable=info, font=("Helvetica", 35))
my_entry.pack(pady=20)
my_entry.get()

# str(EntryAnswer)
# EntryAnswer.pack(pady=20)

# %%
# Create Answer, Next & Hint Buttons

button_frame = Frame(root)
button_frame.pack(pady=20)

answer_button = Button(button_frame, text="Answer", command=answer)
answer_button.grid(row=0, column=0, padx=20)

next_button = Button(button_frame, text="Next", command=next)
next_button.grid(row=0, column=1)

hint_button = Button(button_frame, text="Hint", command=hint)
hint_button.grid(row=0, column=2, padx=20)

# Create Hint Label
hint_label = Label(root, text="")
hint_label.pack(pady=40)

# %%
# Run next function when program starts
next()

# %%
root.mainloop()